[package]
name = "unavi-app"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
bevy = "0.11.3"
bevy_rapier3d = { version = "0.22.0", features = ["simd-stable"] }
