[package]
name = "unavi-wasm"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy = "0.11.3"
unavi-engine = { path = "../engine" }
wasm-bindgen = "0.2.87"
